import org.testng.Assert;
import org.testng.annotations.Test;

/*
 * This Java source file was auto generated by running 'gradle init --type java-library'
 * by 'hadoop' at '7/18/15 8:00 PM' with Gradle 2.4
 *
 * @author hadoop, @date 7/18/15 8:00 PM
 */
public class LibraryTest {
    @Test 
    public void testSomeLibraryMethod() {
        Library classUnderTest = new Library();
        Assert.assertTrue(classUnderTest.someLibraryMethod(), "someLibraryMethod should return 'true'");
    }
}
